---
- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: common
    tags: 
      - common

- hosts: zookeeper
  gather_facts: False
  tasks:
  - import_role:
      name: jdk
    tags: 
      - jdk

- hosts: zookeeper
  gather_facts: False
  tasks:
  - import_role:
      name: zookeeper
    tags: 
      - zk

- hosts: hdp
  gather_facts: False
  tasks:
  - import_role:
      name: hadoop
    tags:
      - hdp
    
- hosts: hdp_namenode
  gather_facts: False
  tasks:
  - import_role:
      name: namenode
    tags:
      - namenode
